---

- hosts: all
  sudo: True

  vars:
    gui_packages: [ 'i3', 'i3lock', 'i3status', 'suckless-tools',
                    'scrot', 'feh', 'imagemagick', 'vlc', 'smtube',
                    'fonts-inconsolata', 'xfonts-terminus',
                    'virt-manager', 'luakit' ]

    cli_packages: [ 'newsbeuter', 'pass', 'uptimed', 'nmap', 'whois',
                    'bind9-host', 'weechat-curses', 'turses' ]

    mail_packages: [ 'mutt', 'isync', 'msmtp', 'urlscan' ]

  tasks:

    - name: Install GUI and CLI packages
      apt:
        name: '{{ item }}'
        state: 'present'
        install_recommends: False
      with_items: gui_packages + cli_packages + mail_packages

    - name: Set xterm as default X terminal emulator
      alternatives:
        name: 'x-terminal-emulator'
        path: '/usr/bin/xterm'

